// @vitest-environment jsdom
/** Minimal ASCII FBX through the parse → buildScene → sceneToThree pipeline. */
import { describe, expect, it } from "vitest";
import { Group, LoadingManager, Mesh } from "three";
import { parseFbx } from "../../../../src/plugins/model/fbx/parse";

const MINIMAL_FBX = `; FBX 7.3.0 project file
; Generated by scratch test
FBXHeaderExtension:  {
	FBXHeaderVersion: 1003
	FBXVersion: 7300
	Creator: "Scratch"
}
GlobalSettings:  {
	Version: 1000
	Properties70:  {
		P: "UpAxis", "int", "Integer", "",1
		P: "UpAxisSign", "int", "Integer", "",1
		P: "FrontAxis", "int", "Integer", "",2
		P: "FrontAxisSign", "int", "Integer", "",1
		P: "CoordAxis", "int", "Integer", "",0
		P: "CoordAxisSign", "int", "Integer", "",1
		P: "UnitScaleFactor", "double", "Number", "",1
	}
}
Objects:  {
	Geometry: 1234560, "Geometry::", "Mesh" {
		Vertices: *9 {
			a: 0,0,0,1,0,0,0,1,0
		}
		PolygonVertexIndex: *3 {
			a: 0,1,-3
		}
		GeometryVersion: 124
		LayerElementNormal: 0 {
			Version: 101
			Name: ""
			MappingInformationType: "ByPolygonVertex"
			ReferenceInformationType: "Direct"
			Normals: *9 {
				a: 0,0,1,0,0,1,0,0,1
			}
		}
		LayerElementUV: 0 {
			Version: 101
			Name: "UVMap"
			MappingInformationType: "ByPolygonVertex"
			ReferenceInformationType: "IndexToDirect"
			UV: *6 {
				a: 0,0,1,0,1,1
			}
			UVIndex: *3 {
				a: 0,1,2
			}
		}
		LayerElementMaterial: 0 {
			Version: 101
			Name: ""
			MappingInformationType: "AllSame"
			ReferenceInformationType: "IndexToDirect"
			Materials: *1 {
				a: 0
			}
		}
		Layer: 0 {
			Version: 100
			LayerElement:  {
				Type: "LayerElementNormal"
				TypedIndex: 0
			}
			LayerElement:  {
				Type: "LayerElementMaterial"
				TypedIndex: 0
			}
			LayerElement:  {
				Type: "LayerElementUV"
				TypedIndex: 0
			}
		}
	}
	Model: 1234561, "Model::mesh", "Mesh" {
		Version: 232
		Properties70:  {
			P: "Lcl Translation", "Lcl Translation", "", "A",0,0,0
			P: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0
			P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1
		}
		Shading: T
		Culling: "CullingOff"
	}
}
Connections:  {
	C: "OO",1234560,1234561
	C: "OO",1234561,0
}
`;

describe("fbx scratch repro", () => {
  it("parses and converts a minimal ascii fbx", () => {
    const buffer = new TextEncoder().encode(MINIMAL_FBX).buffer as ArrayBuffer;
    const model = parseFbx(buffer, "http://localhost/", new LoadingManager(), new AbortController().signal);
    expect(model).toBeInstanceOf(Group);
    expect(model.userData.fbxVersion).toBe(7300);
    let vertices = 0;
    let uvs = 0;
    model.traverse(object => {
      if (object instanceof Mesh) {
        vertices += object.geometry.getAttribute("position")?.count ?? 0;
        uvs += object.geometry.getAttribute("uv")?.count ?? 0;
      }
    });
    expect(vertices).toBe(3);
    expect(uvs).toBe(3);
  });
});
